worker_processes  1;
error_log /dev/stdout warn;

events {
    worker_connections  1024;
}

http {
    server_tokens off;
    default_type  application/octet-stream;
    #access_log    /dev/stdout;

    sendfile           on;
    keepalive_timeout  65;

    upstream backend {
        server wol:8089;
    }

    server {
        server_name wol.eftasgmbh.local;
        listen 8090 ssl;
        ssl_certificate /etc/nginx/wol.eftasgmbh.local.pem;
        ssl_certificate_key /etc/nginx/wol.eftasgmbh.local.pem;
        ssl_verify_client off;
        ssl_protocols TLSv1.2 TLSv1.3;
        # Some security headers...
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options nosniff;
        # Disable strict transport security for now. You can uncomment the following
        # line if you understand the implications.
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";

        location / {
            limit_except GET HEAD POST { deny all; }
            add_header X-Frame-Options SAMEORIGIN;
            add_header X-XSS-Protection "1; mode=block";
            proxy_pass  http://backend/;
            proxy_set_header Host $http_host;
            proxy_set_header X_FORWARDED_PROTO https;
        }
    }
}
